steamKey: 0D10072DF5954D20F515787F43532993
version: latest
pinnedPackages:
  ssri: 8.0.1
  cacache: 16.1.3
  passport-steam: 1.0.17
bots:
  simplebot: "screepsbot-zeswarm"
  overmind: "./bots/overmind/dist" # On windows path needs to be .\\bots\\overmind\\dist
extraPackages:
  morgan: "*"
localMods: ./mods
backup:
  dirs:
  - tests
serverConfig:
  welcomeText:  |
    <style>.screepsplus h1{  text-align: center; }</style>
    <div class="screepsplus">
    <h1>ScreepsPlus</h1>
    Wecome to the ScreepsPlus private server.<br>
    Mods include screepsmod-auth and several custom mods to enable email notifications, control tickrate, power banks, portals, and other internal improvements.<br><br>
    <div style="text-align: center">
    This server is funded by backers on Patreon. <br>
    <a target="_blank" href="https://www.patreon.com/bePatron?u=6867142" ><img src="https://c5.patreon.com/external/logo/become_a_patron_button.png"></a>
    </div>
  constants:
    TEST_CONSTANT: 123
  tickRate: 1000
cli: # used for configuring cli client
  host: testing.hosting.screepspl.us
  port: 443 # https assumed when using 443
  username: admin
  password: notARealPassword
